查询条件自动放宽
从数据库中按照模型型号过滤模型数据, 如果模型型号不存在, 将从右向左逐次递减一个字符搜索, 一旦有数据就返回结果集, 直到字符为空时仍查不出数据, 返回空结果集.

假设模型型号有1, 12, 123. 
1. 输入1234时, 返回123 
2. 输入12时, 返回12, 123 
3. 输入22时, 返回空结果集.

注意: 查询条件存在特殊字符

思路: 在while循环中, 利用动态sql查出结果集数量, 判断递减条件或是退出.
CREATE TABLE TESTTAB
    ( MODEL_NUMBER VARCHAR2(20)
    );
    /
INSERT INTO TESTTAB (MODEL_NUMBER)
SELECT   MODENUM
  FROM
    (SELECT '11' MODENUM FROM DUAL
    UNION ALL
    SELECT '12' MODENUM FROM DUAL
    UNION ALL
    SELECT '123' MODENUM FROM DUAL
    );
    /
DECLARE
  -- DYNAMIC SQL
  V_SQL VARCHAR2 (20000):= 'SELECT A.MODEL_NUMBER FROM TESTTAB A WHERE 1=1 ' ;
  V_SQLTMP VARCHAR2 (20000) ;
  -- FILTER CONDITION
  OUT_MODELNUMBER VARCHAR2 (20000):='1234' ;
  V_COUNT NUMBER:=0;
  -- PRINT DYNAMIC SQL
  CSR SYS_REFCURSOR;
  V_MOD_NUM VARCHAR2(2000);
BEGIN
  WHILE V_COUNT=0
  LOOP
    V_SQLTMP:=V_SQL;
    IF OUT_MODELNUMBER IS NOT NULL THEN
      -- ESCAPE SPECIAL CHARACTER: MODEL_NUMBER LIKE Q'/1'/' ||'%';
      V_SQLTMP:=V_SQL || ' AND UPPER(A.MODEL_NUMBER) LIKE Q''/' || UPPER (OUT_MODELNUMBER) || '/''||''%'' ';
    ELSE
      V_SQL:=V_SQL || ' AND  1=2 ';
      EXIT;
    END IF;
    EXECUTE IMMEDIATE ' SELECT COUNT(1) FROM  (' || V_SQLTMP ||')' INTO V_COUNT;
    IF V_COUNT>0 THEN
      -- EXIT
      V_SQL:=V_SQLTMP;
    ELSE
      OUT_MODELNUMBER:=SUBSTR (OUT_MODELNUMBER, 1, LENGTH (OUT_MODELNUMBER)-1) ;
    END IF;
  END LOOP;
  --DBMS_OUTPUT.PUT_LINE (V_SQL) ;
  -- PRINT DYNAMIC RESULT
  OPEN CSR FOR V_SQL;
  LOOP
    FETCH CSR INTO V_MOD_NUM ;
    EXIT
  WHEN CSR%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('V_MOD_NUM=''' || V_MOD_NUM || ''' ' );
  END LOOP;
  CLOSE CSR;
END; 