kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-local-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi
  storageClassName: local-storage

  # kubectl create -f local-pvc.yaml 