apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: block-service
  resources:
    requests:
      storage: 30Gi


# kubectl create -f pvc.yaml
# kubectl describe pvc claim1
# kubectl describe pv pvc-e5578707-c626-11e6-baf6-08002729a32b