# Generated by Django 2.2.2 on 2019-08-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('passwd', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'UserTest',
            },
        ),
    ]
