apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx

  # Service 又是如何被访问的
  # 1, Service 的 VIP（Virtual IP，即：虚拟 IP）方式
  # 2, 第二种方式，就是以 Service 的 DNS 方式
  #  Service DNS 的方式下，具体还可以分为两种处理方法;
  #  1. Normal Service, 解析到 my-svc 这个 Service 的 VIP
  #  2. Headless Service, Headless Service 不需要分配一个 VIP，而是可以直接以 DNS 记录的方式解析出被代理 Pod 的 IP 地址


  # !!! Headless Service，其实仍是一个标准 Service 的 YAML 文件。只不过，它的 clusterIP 字段的值是：None